'use client'

import { useState } from 'react'
import { FileSignature, ExternalLink, Loader2, CheckCircle2 } from 'lucide-react'

interface ContractViewerProps {
  contractId: string
  supplierId: string
  signingUrl: string
  status: string
}

export function ContractViewer({ contractId, signingUrl, status }: ContractViewerProps) {
  const [isSigning, setIsSigning] = useState(false)
  const isPending = status === 'SENT' || status === 'DRAFT'

  // MVP Mock Click Handler to simulate Webhook execution locally
  const handleMockSign = async () => {
    setIsSigning(true)
    try {
      // Intentionally call our own webhook mock endpoint bypassing the third party provider
      // using the OPENSIGN_WEBHOOK_SECRET locally to trick it into approving the sign
      const reqIdMatch = signingUrl.match(/sign\/([^?]+)/)
      const requestId = reqIdMatch ? reqIdMatch[1] : contractId

      await fetch('/api/webhooks/opensign', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-opensign-signature': 'TEST_SECRET_MOCK' // Relies on dev env matching this
        },
        body: JSON.stringify({
          event_type: 'signature_request_signed',
          request_id: requestId
        })
      })

      // Force reload to let middleware re-evaluate upgraded status
      window.location.reload()
    } catch (e) {
      console.error(e)
    } finally {
      setIsSigning(false)
    }
  }

  return (
    <div className="bg-[var(--color-bg-secondary)] border border-[var(--color-border)] rounded-xl shadow-sm overflow-hidden">
      <div className="p-6 border-b border-[var(--color-border)] flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-[var(--color-primary-light)] rounded-lg text-[var(--color-primary)]">
            <FileSignature className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[var(--color-text-primary)]">Collaboration Agreement</h3>
            <p className="text-sm text-[var(--color-text-secondary)]">
              Reference: {contractId.split('-')[0].toUpperCase()}
            </p>
          </div>
        </div>
        <div>
          {status === 'SIGNED' ? (
            <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-[var(--color-success)]/10 text-[var(--color-success)]">
              <CheckCircle2 className="w-4 h-4 mr-1.5" />
              Signed & Executed
            </span>
          ) : (
            <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-[var(--color-primary-light)] text-[var(--color-primary)]">
              Pending Signature
            </span>
          )}
        </div>
      </div>

      <div className="p-8 bg-[var(--color-bg-primary)]">
        {isPending ? (
          <div className="max-w-xl mx-auto text-center space-y-6">
            <div className="p-6 bg-[var(--color-bg-secondary)] rounded-xl border border-[var(--color-border)]">
              <h4 className="font-medium text-[var(--color-text-primary)] mb-2">Ready for Review</h4>
              <p className="text-[var(--color-text-secondary)] text-sm mb-6">
                Your partnership agreement has been generated by the uhomes BD team. Please review the terms and complete the electronic signature to activate your account.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <a 
                  href={signingUrl} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="inline-flex items-center justify-center px-5 py-2.5 rounded-lg border border-[var(--color-border)] hover:bg-[var(--color-bg-primary)] text-[var(--color-text-primary)] font-medium transition-colors"
                >
                  <ExternalLink className="w-4 h-4 mr-2" />
                  View Original Contract
                </a>
                
                <button
                  onClick={handleMockSign}
                  disabled={isSigning}
                  className="inline-flex items-center justify-center px-5 py-2.5 rounded-lg bg-[var(--color-primary)] text-white hover:bg-[var(--color-primary-hover)] font-medium transition-colors disabled:opacity-70"
                >
                  {isSigning ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Processing...</>
                  ) : (
                    'Sign Contract (Mock)'
                  )}
                </button>
              </div>
            </div>
            <p className="text-xs text-[var(--color-text-secondary)]">
              By clicking &quot;Sign Contract&quot;, you agree to the Terms of Service and Privacy Policy. The electronic signature is legally binding.
            </p>
          </div>
        ) : (
           <div className="text-center py-12">
             <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-[var(--color-success)]/10 text-[var(--color-success)] mb-4">
                <CheckCircle2 className="w-8 h-8" />
             </div>
             <h3 className="text-xl font-semibold text-[var(--color-text-primary)] mb-2">Account Activation Complete</h3>
             <p className="text-[var(--color-text-secondary)]">
               You will be redirected to the supplier portal momentarily.
             </p>
           </div>
        )}
      </div>
    </div>
  )
}
